01-Python-Crash-Course/
02-Numpy/
03-Pandas/
04-Matplotlib/
05-Seaborn/
06-Capstone-Project/
07-Overview-of-Machine-Learning/
08-Linear-Regression-Models/
09-Feature-Engineering/
10-Cross-Val-and-LinReg-Project/
11-Logistic-Regression-Models/
12-K-Nearest-Neighbors/
13-Support-Vector-Machines/
14-Decision-Trees/
15-Random-Forests/
16-Boosted-Trees/
17-Supervised-Learning-Capstone-Project/
18-Naive-Bayes-and-NLP/
19-Unsupervised-Learning-Overview/
20-Kmeans-Clustering/
21-Hierarchal-Clustering/
21-Hierarchical-Clustering/
22-DBSCAN/
23-PCA-Principal-Component-Analysis/
24-Model-Deployment/
